### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [JulesLevy/bootstrap-test-hw#1]
Jules,

Nice work on this! I think it turned out great. Only recommendation I have for you is to avoid stuff like this:

```css
.bodyspace {
  margin: 80px 15px 20px 5%;
}
```

You generally don't want to use percentage-based margins, as they are difficult to anticipate. In one container a 5% margin could be 20px, whereas in another container 5% could equate to 2000px.
